### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by RomiTorres** [4GeeksAcademy/abielsaf-instagram-feed-bootstrap#1]
Ángel, muy buen trabajo, solo deberias corregir que el botón de CREATE A NEW POST este hacia la derecha, peqgado al otro. El dropdown debe desplegarse hacia el otro lado.
Espero las correcciones! Me gusta como trabajas!!!

**Comment by abielsaf** [comment]
Gracias por el feedback, queda modificado.
